CROSSING-7064; version of docker installed is 17.05.0-ce
UKHomeOffice/ansible-role-docker pull request #2
Opened 2017-07-25 15:51 UTC by shazChaudhry

CROSSING-7064

- Docker role is passing
- The ansible role will install docker v17.06.0 ce

2017-07-25 15:57 UTC, sirv1ne commented on tasks/Debian.yml
>      - apt-transport-https
Could you remove these old dependencies please! They don't seem to be required anymore so should be cleaned up :)

2017-07-26 09:09 UTC, sirv1ne requested changes

2017-07-26 09:09 UTC, sirv1ne commented on tasks/Debian.yml
>      - "linux-image-extra-virtual-lts-{{ ansible_distribution_release }}"
Could you remove these old dependencies please! They don't seem to be required anymore so should be cleaned up :)

2017-07-26 09:41 UTC, sirv1ne commented on tasks/Debian.yml
>      - "linux-image-extra-virtual-lts-{{ ansible_distribution_release }}"
Packages to go are: "linux-image-extra-virtual", "linux-image-extra-virtual-lts-{{ ansible_distribution_release }}", "python", "python-pip", "python-httplib2". None of these are listed as dependencies in https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository.

2017-07-26 11:08 UTC, shazChaudhry commented
Removed packages not required or used anywhere else within the role for docker installation. As discussed, curl package is not needed and I have left "python, python-pip, python-httplib2" alone as presence for some of the modules is checked in the main.yml

2017-07-26 11:33 UTC, sirv1ne commented
LGTM

2017-07-26 11:33 UTC, sirv1ne approved these changes

2017-07-26 11:34 UTC, merged